image: registry.gitlab.com/goodok-chat/messaging-framework:latest
variables:
  DEBIAN_FRONTEND: noninteractive
stages:
  - build
Build:
  stage: build
  before_script:
    - mkdir build && cd build && mkdir -p proto
    - conan profile new goodok-profile --detect
    - conan profile update settings.compiler.version=9.3 goodok-profile
    - conan profile update settings.compiler.libcxx=libstdc++11 goodok-profile
    - conan install -s build_type=Release .. --build=missing --profile goodok-profile
    - cd ..
  script:
    - cd build
    - cmake ..
    - cmake --build . -- -j 4
    - cmake --build . --target test
    - cmake --build . --target package
  artifacts:
    paths:
      - pwd
      - build/Messaging-framework-0.1.3-Linux.deb