image: ubuntu:focal
variables:
  DEBIAN_FRONTEND: noninteractive
stages:
  - build
Conan:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y python3-pip cmake
    - pip3 install conan
    - source ~/.profile
  script:
    - mkdir build && cd build && mkdir -p proto
    - conan profile new goodok-profile --detect
    - conan profile update settings.compiler.version=9.3 goodok-profile
    - conan profile update settings.compiler.libcxx=libstdc++11 goodok-profile
    - conan install -s build_type=Release .. --build=missing --profile goodok-profile
    - cmake ..
    - cmake --build .
    - cmake --build . --target test
    - cmake --build . --target package