language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - graphviz
            - doxygen
            - python-pip
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_DIR=build
        - APP_NAME=protocol
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - pip install conan
        - source ~/.profile

      script:
        - mkdir -p ${BUILD_DIR}  && cd ${BUILD_DIR} && mkdir -p proto
        - conan profile new goodok-profile --detect
        - conan profile update settings.compiler.version=9.3 goodok-profile
        - conan profile update settings.compiler.libcxx=libstdc++11 goodok-profile
        - conan install -s build_type=Release .. --build=missing --profile goodok-profile
        - cmake ..
        - cmake --build .
        - cmake --build . --target package

#        - >-
#            if [[ "$TRAVIS_BRANCH" = "dev" && -n "$TRAVIS_BUILD_DOCS" ]] ; then
#              cd $TRAVIS_BUILD_DIR
#              echo 'Generating Doxygen code documentation...'
#              # Redirect both stderr and stdout to the log file AND the console.
#              doxygen doc/Doxyfile 2>&1 | tee doxygen.log
#              curl -T ${TRAVIS_BUILD_DIR}/${BUILD_DIR}/appchat-server-0.7.$TRAVIS_BUILD_NUMBER-Linux.deb -uk-morozov:$BINTRAY_API_KEY "https://api.bintray.com/content/k-morozov/AppChat/server/server-linux/appchat-server-0.7.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
#              curl -T ${TRAVIS_BUILD_DIR}/${BUILD_DIR}/appchat-client-0.7.$TRAVIS_BUILD_NUMBER-Linux.deb -uk-morozov:$BINTRAY_API_KEY "https://api.bintray.com/content/k-morozov/AppChat/client/client-linux/appchat-client-0.7.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
#            fi
#      before_deploy:
#        - git config --local user.name "k-morozov"
#        - git config --local user.email "morozov-kst@yandex.ru"
#        - git tag 0.7.$TRAVIS_BUILD_NUMBER-Linux
#      deploy:
#        - provider: releases
#          api_key: $GITHUB_API_KEY
#          file: AppChat-0.7.$TRAVIS_BUILD_NUMBER-Linux.tar
#          skip_cleanup: true
#          on:
#            branch: release
#        - provider: pages
#          skip_cleanup: true
#          token: $GITHUB_API_KEY
#          keep_history: true
#          local_dir: docs/html